[package]
name = "imp_hvm"
version = "0.1.0"
edition = "2021"

[dependencies]
hvm = "1.0.0"
lalrpop-util = {version="0.19.7", features=["lexer"]}
regex = "1"

[build-dependencies]
lalrpop = "0.19.7"

[dev-dependencies]
pretty_assertions = "1.3.0"
walkdir = "2"
